salida: persona.o main.o 
	g++ -o salida partida.o persona.o main.o 
main.o: main.cpp 
	g++ -c main.cpp
persona.o:persona.cpp 
	g++ -c persona.cpp 
partida.o:partida.cpp 
	g++ -c partida.cpp 
clear:
	del* .o